#!/usr/bin/env python3
"""
BountyForge HTTP pool - shared async client + response classification heuristics.

Upstream ships five engines that import this module (auth_manager,
race_engine, smuggle_engine, ssrf_engine, waf_detector) but the file itself
was never committed, so every one of them exits at startup with
"[!] http_pool.py required".  This implements the API those call sites use:

    pool = HTTPPool(max_connections=30, timeout=15)
    await pool.start()
    result = await pool.request("GET", url, headers={...},
                                json_data=..., data=..., allow_redirects=True)
    await pool.stop()

    pool.random_ua()
    pool.is_waf_block(result)
    pool.is_internal_response(result, baseline)
    pool.is_metadata_response(result)
    await pool.detect_http_version(url)      # {"h1": bool, "h2": bool}

Status codes on failure (both are probed by auth_manager):
    -1  connection / TLS / protocol error
    -3  timeout

Set BF_SSL_VERIFY=0 to accept self-signed and mismatched certificates,
which staging and internal targets commonly present.
"""

from __future__ import annotations

import asyncio
import os
import random
import ssl
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple, Union
from urllib.parse import urlparse

import aiohttp

STATUS_NET_ERROR = -1
STATUS_TIMEOUT = -3

_FALLBACK_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
)

# Phrases WAFs emit in the response body when they reject a probe.
_WAF_BODY_SIGS = (
    "access denied",
    "you have been blocked",
    "attention required! | cloudflare",
    "the request could not be satisfied",
    "requested url was rejected",
    "the requested url was rejected by this server",
    "not acceptable",
    "generated by fastly",
    "varnish error",
    "web application firewall",
    "mod_security",
    "modsecurity",
    "aws waf",
    "blocked by security policy",
    "request blocked",
)

# Server header fragments that identify a WAF in front of the origin.
_WAF_SERVER_SIGS = (
    "cloudflare",
    "akamai",
    "akamaighost",
    "fastly",
    "incapsula",
    "sucuri",
    "barracuda",
    "bigip",
    "f5",
    "imperva",
    "wallarm",
    "stackpath",
    "keycdn",
)

# Header names whose presence alone indicates an edge/WAF layer.
_WAF_EDGE_HEADERS = (
    "cf-ray",
    "cf-cache-status",
    "x-sucuri-id",
    "x-sucuri-cache",
    "x-akamai-transformed",
    "x-cdn",
    "x-iinfo",
    "x-cache",
    "x-fastly-request-id",
)

# Response markers that mean we reached an internal service rather than
# the public origin.
_INTERNAL_BODY_SIGS = (
    "root:x:0:0",
    "daemon:x:",
    "/bin/bash",
    "www-data:x:",
    "docker",
    "kubernetes",
    "<title>localhost",
    "<title>127.0.0.1",
    "internal server error",
    "apache tomcat",
    "tomcat manager",
    "jenkins",
    "grafana",
    "prometheus",
    "minio",
    "phpmyadmin",
    "internal only",
    "not publicly accessible",
    "169.254.169.254",
)

# Cloud instance metadata service fingerprints.
_METADATA_SIGS = (
    "ami-id",
    "instance-id",
    "instance-type",
    "meta-data/",
    "user-data",
    "iam/security-credentials",
    "\"code\" : \"success\"",
    '"code": "success"',
    "computemetadata",
    "metadata-flavor",
    "signedprincipal",
    "managed identity",
    "subscriptionid",
    "resourceid",
    "virtual machine",
    "list of routes",
    "hostname",
)


class Headers(dict):
    """Case-insensitive response headers; repeated fields are comma-joined."""

    def __init__(self, items: Union[Mapping, Sequence, None] = None) -> None:
        super().__init__()
        if items is None:
            return
        pairs: Sequence[Tuple[Any, Any]]
        if isinstance(items, Mapping):
            pairs = list(items.items())
        else:
            pairs = list(items)
        for key, value in pairs:
            name = str(key).lower()
            text = "" if value is None else str(value)
            if name in self:
                self[name] = f"{self[name]}, {text}"
            else:
                self[name] = text

    @staticmethod
    def _norm(key: Any) -> str:
        return str(key).lower()

    def get(self, key, default=None):  # type: ignore[override]
        return super().get(self._norm(key), default)

    def __contains__(self, key) -> bool:  # type: ignore[override]
        return super().__contains__(self._norm(key))

    def __getitem__(self, key):  # type: ignore[override]
        return super().__getitem__(self._norm(key))

    def __setitem__(self, key, value):  # type: ignore[override]
        super().__setitem__(self._norm(key), value)


@dataclass
class HTTPResult:
    """One HTTP exchange.  Error statuses are negative (see module docstring)."""

    url: str = ""
    method: str = "GET"
    status: int = STATUS_NET_ERROR
    headers: Headers = field(default_factory=Headers)
    body: str = ""
    duration_ms: float = 0.0
    error: str = ""

    @property
    def ok(self) -> bool:
        return 200 <= self.status < 400

    @property
    def failed(self) -> bool:
        return self.status < 0

    def header(self, name: str, default: str = "") -> str:
        return self.headers.get(name, default) or default

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return (
            f"HTTPResult({self.method} {self.url} -> {self.status} "
            f"{self.duration_ms:.0f}ms{', ' + self.error if self.error else ''})"
        )


class HTTPPool:
    """Pooled aiohttp client with the response heuristics the engines expect.

    Not thread-safe: use it from a single asyncio event loop, which is how
    every caller drives it (asyncio.run(main())).
    """

    def __init__(
        self,
        max_connections: int = 10,
        timeout: float = 15,
        proxy: Optional[str] = None,
        verify_ssl: Optional[bool] = None,
    ) -> None:
        self.max_connections = max(1, int(max_connections))
        self.timeout = float(timeout)
        self.proxy = proxy or os.environ.get("BF_HTTP_PROXY") or None
        if verify_ssl is None:
            verify_ssl = os.environ.get("BF_SSL_VERIFY", "1") not in ("0", "false", "no")
        self.verify_ssl = bool(verify_ssl)
        self._session: Optional[aiohttp.ClientSession] = None
        self._connector: Optional[aiohttp.TCPConnector] = None
        self._ssl_ctx: Optional[ssl.SSLContext] = None
        self._lock = asyncio.Lock()
        self._closed = False
        self.request_count = 0

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def start(self) -> "HTTPPool":
        """Create the underlying session.  Idempotent."""
        if self._session is not None and not self._session.closed:
            return self
        async with self._lock:
            if self._session is not None and not self._session.closed:
                return self
            self._closed = False
            self._ssl_ctx = self._build_ssl_context()
            self._connector = aiohttp.TCPConnector(
                limit=self.max_connections,
                limit_per_host=0,
                ttl_dns_cache=300,
                enable_cleanup_closed=True,
                ssl=self._ssl_ctx,
            )
            timeout = aiohttp.ClientTimeout(total=self.timeout)
            self._session = aiohttp.ClientSession(
                connector=self._connector,
                timeout=timeout,
                auto_decompress=True,
                cookie_jar=aiohttp.DummyCookieJar(),
                trust_env=True,
            )
        return self

    async def stop(self) -> None:
        """Close the session and release sockets."""
        async with self._lock:
            self._closed = True
            session, self._session = self._session, None
            connector, self._connector = self._connector, None
        if session is not None and not session.closed:
            await session.close()
        if connector is not None:
            await connector.close()

    async def __aenter__(self) -> "HTTPPool":
        return await self.start()

    async def __aexit__(self, *exc_info) -> None:
        await self.stop()

    def _build_ssl_context(self, alpn: Sequence[str] = ("http/1.1",)) -> ssl.SSLContext:
        """Build a TLS context advertising only protocols we can actually speak.

        The client connector must offer http/1.1 alone: advertising h2 to a
        server that accepts it makes it send HTTP/2 frames that aiohttp (which
        has no h2 transport) then rejects as a bad status line.  The h2 probe
        uses its own context purely to read back the negotiated protocol.
        """
        if self.verify_ssl:
            ctx = ssl.create_default_context()
        else:
            ctx = ssl._create_unverified_context()  # noqa: SLF001 - explicit opt-out
        try:
            ctx.set_alpn_protocols(list(alpn))
        except NotImplementedError:  # pragma: no cover - platform dependent
            pass
        return ctx

    async def _ensure_session(self) -> aiohttp.ClientSession:
        if self._session is None or self._session.closed:
            await self.start()
        assert self._session is not None
        return self._session

    # ------------------------------------------------------------------
    # Requests
    # ------------------------------------------------------------------

    async def request(
        self,
        method: str = "GET",
        url: str = "",
        headers: Optional[Mapping[str, str]] = None,
        json_data: Any = None,
        data: Union[str, bytes, Mapping, None] = None,
        allow_redirects: bool = True,
        timeout: Optional[float] = None,
        proxy: Optional[str] = None,
    ) -> HTTPResult:
        """Perform one request and always return an HTTPResult.

        Network failures never raise: they come back as status -1 / -3 so the
        engines can treat transport errors as data (e.g. race-condition
        status distributions).
        """
        method = (method or "GET").upper()
        url = url or ""
        session = await self._ensure_session()

        req_headers = Headers(headers) if headers else Headers()
        if "user-agent" not in req_headers:
            req_headers["user-agent"] = self.random_ua()
        if "accept" not in req_headers:
            req_headers["accept"] = "*/*"

        req_timeout = aiohttp.ClientTimeout(
            total=self.timeout if timeout is None else timeout
        )
        start = time.perf_counter()
        self.request_count += 1
        try:
            async with session.request(
                method,
                url,
                headers=dict(req_headers),
                json=json_data,
                data=data,
                allow_redirects=allow_redirects,
                timeout=req_timeout,
                proxy=proxy if proxy is not None else self.proxy,
            ) as resp:
                raw = await resp.read()
                charset = resp.charset or "utf-8"
                try:
                    body = raw.decode(charset, errors="replace")
                except LookupError:
                    body = raw.decode("utf-8", errors="replace")
                return HTTPResult(
                    url=str(resp.url),
                    method=method,
                    status=resp.status,
                    headers=Headers(resp.headers.items()),
                    body=body,
                    duration_ms=(time.perf_counter() - start) * 1000.0,
                )
        except asyncio.TimeoutError:
            return self._error(method, url, STATUS_TIMEOUT,
                               f"timeout after {req_timeout.total}s", start)
        except aiohttp.ClientError as exc:
            return self._error(method, url, STATUS_NET_ERROR, str(exc) or type(exc).__name__, start)
        except ssl.SSLError as exc:
            return self._error(method, url, STATUS_NET_ERROR, f"ssl: {exc}", start)
        except OSError as exc:
            return self._error(method, url, STATUS_NET_ERROR, str(exc) or type(exc).__name__, start)
        except Exception as exc:  # pragma: no cover - defensive, never crash a scan
            return self._error(method, url, STATUS_NET_ERROR,
                               f"{type(exc).__name__}: {exc}", start)

    @staticmethod
    def _error(method: str, url: str, status: int, message: str, start: float) -> HTTPResult:
        return HTTPResult(
            url=url,
            method=method,
            status=status,
            headers=Headers(),
            body="",
            duration_ms=(time.perf_counter() - start) * 1000.0,
            error=message,
        )

    def random_ua(self) -> str:
        """A plausible browser User-Agent, preferring the shared OPSEC pool."""
        try:
            from tools.opsec import UA_POOL  # noqa: PLC0415 - lazy to avoid a cycle
            if UA_POOL:
                return random.choice(UA_POOL)
        except Exception:
            pass
        return _FALLBACK_UA

    # ------------------------------------------------------------------
    # Response classification
    # ------------------------------------------------------------------

    @staticmethod
    def _body(result: HTTPResult, limit: int = 8192) -> str:
        text = result.body or ""
        return text[:limit].lower()

    @staticmethod
    def _failed(result: HTTPResult) -> bool:
        return result.status < 0

    def is_waf_block(self, result: HTTPResult) -> bool:
        """True when the response looks like a WAF/edge rejecting the probe.

        Heuristic: signature header, signature body text, or a hard-reject
        status (406/419/429/503).  A bare 403 is not enough on its own -
        origins return it too - so it only counts alongside edge evidence.
        """
        if self._failed(result):
            return False

        header_blob = " ".join(
            str(v) for k, v in result.headers.items()
            if k in _WAF_EDGE_HEADERS or k == "server"
        ).lower()
        if any(sig in header_blob for sig in _WAF_SERVER_SIGS):
            return True
        if any(h in result.headers for h in _WAF_EDGE_HEADERS):
            # Edge header + a reject status is a strong WAF signal.
            if result.status in (403, 406, 419, 429, 451, 503):
                return True

        body = self._body(result)
        if any(sig in body for sig in _WAF_BODY_SIGS):
            return True

        if result.status in (406, 419, 429, 451, 503):
            return True
        return False

    def is_internal_response(self, result: HTTPResult, baseline: Optional[HTTPResult] = None) -> bool:
        """True when the response suggests we reached an internal resource.

        Two signals, either of which is enough:
          * explicit internal-service markers in the body;
          * a material difference from the baseline response captured with an
            inert payload - different status, or body length moving by more
            than 30% while the content hash also changes.
        """
        if self._failed(result):
            return False

        body = result.body or ""
        low = body[:16384].lower()
        if any(sig in low for sig in _INTERNAL_BODY_SIGS):
            return True

        if baseline is None or self._failed(baseline) or not baseline.body:
            return False

        base = baseline.body or ""
        if result.status != baseline.status:
            # A status flip is meaningful whenever the new body is real content.
            if body.strip() and result.status in (200, 301, 302, 500, 502):
                return True
            if result.status in (200, 401, 403, 404, 500) and len(body) != len(base):
                return True

        if not body or not base:
            return False
        if body == base:
            return False

        delta = abs(len(body) - len(base)) / max(len(base), 1)
        if delta > 0.30:
            return True
        # Small bodies can differ without meaning much; require a real change.
        if delta > 0.05 and hash(body) != hash(base) and result.status == baseline.status:
            return len(body) > 0 and body[:512] != base[:512]
        return False

    def is_metadata_response(self, result: HTTPResult) -> bool:
        """True when the body carries a cloud instance-metadata fingerprint."""
        if self._failed(result):
            return False
        if result.status != 200:
            return False
        body = self._body(result, 32768)
        if not body.strip():
            return False
        hits = sum(1 for sig in _METADATA_SIGS if sig in body)
        # One generic word ("hostname") proves nothing on its own.
        if hits >= 2:
            return True
        strong = (
            "ami-id", "iam/security-credentials", "computemetadata",
            "meta-data/", "managed identity", "signedprincipal",
        )
        return any(sig in body for sig in strong)

    # ------------------------------------------------------------------
    # Protocol detection
    # ------------------------------------------------------------------

    async def detect_http_version(self, url: str) -> Dict[str, bool]:
        """Report HTTP/1.1 and HTTP/2 support: {"h1": bool, "h2": bool}.

        h1 comes from a real request (aiohttp speaks HTTP/1.1 only).  h2 comes
        from a TLS ALPN negotiation, so it needs no h2 package; for cleartext
        URLs we fall back to the Alt-Svc header.
        """
        info: Dict[str, bool] = {"h1": False, "h2": False}
        parsed = urlparse(url)
        if not parsed.hostname:
            return info

        probe = await self.request("GET", url, allow_redirects=True)
        info["h1"] = not self._failed(probe)

        alt_svc = probe.header("alt-svc", "")
        if "h2" in alt_svc.lower():
            info["h2"] = True
            return info

        if parsed.scheme == "https":
            info["h2"] = await self._alpn_supports_h2(
                parsed.hostname, parsed.port or 443
            )
        return info

    async def _alpn_supports_h2(self, host: str, port: int) -> bool:
        """Ask TLS which protocol the server will accept over ALPN."""
        # Separate context: this one must offer h2 so the server can pick it.
        ctx = self._build_ssl_context(alpn=("h2", "http/1.1"))
        writer = None
        try:
            _, writer = await asyncio.wait_for(
                asyncio.open_connection(host, port, ssl=ctx, server_hostname=host),
                timeout=min(self.timeout, 10.0),
            )
            ssl_obj = writer.get_extra_info("ssl_object")
            if ssl_obj is None:
                return False
            return ssl_obj.selected_alpn_protocol() == "h2"
        except Exception:
            return False
        finally:
            if writer is not None:
                try:
                    writer.close()
                    await writer.wait_closed()
                except Exception:
                    pass


__all__ = ["HTTPPool", "HTTPResult", "Headers",
           "STATUS_NET_ERROR", "STATUS_TIMEOUT"]
